apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: cloud-native-backend
    newName: vishalkaojiya/cloud-native-backend
    newTag: "1.0"

replicas:
  - name: backend
    count: 1
