apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

replicas:
  - name: backend
    count: 2
  - name: frontend
    count: 2
    
patches:
  - path: nginx-service-patch.yaml