apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-native-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vishukanojiya/cloud-native-devops-platform.git
    targetRevision: main
    path: kubernetes/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true